name: Working Directory

on: [push]

defaults:
  run:
    shell: bash

jobs:
  display-wd-info:
      runs-on: ubuntu-latest
      steps:
        - name: Display working directory
          run: |
            pwd
            ls -a
            echo "$GITHUB_WORKSPACE"
            echo "$GITHUB_REPOSITORY"
            echo "$GITHUB_SHA"

  display-wd-info-windows:
      runs-on: windows-latest
      defaults:
        run:
          shell: pwsh
      steps:
        - name: Display working directory
          run: |
            pwd
            Get-location
            echo "$env:GITHUB_WORKSPACE"
            echo "$env:GITHUB_REPOSITORY"
            echo "$env:GITHUB_SHA"

        - name: Python Shell
          shell: python
          run: |
                import platform
                print(platform.processor())